### ISSUE TITLE
gConfigMap Does Not Initialize A ConfigMap Element With d2gsconf.d2dbsipstr

### ISSUE THREAD

**Issue by RElesgoe** [swordow/d2gs110#1]
The 4th element in the `gConfigMap` array should be initialized to:
`{REGKEY_D2DBSIP					, 04, "192.168.1.1" , d2gsconf.d2dbsipstr},`
instead of:
`{REGKEY_D2DBSIP					, 04, "192.168.1.1" , d2gsconf.d2csipstr}`

https://github.com/swordow/d2gs110/blob/master/sources/config.c#L32

**Comment by swordow** [comment]
fixed, thanks. :-)
